### ISSUE TITLE
Projekt gotowy do oceny

### ISSUE THREAD

**Issue by igorbzzz** [LiMo2344321/Projekt-psio#14]

**Comment by JOtworowski** [comment]
Projekt wykonany poprawnie. Z uwagi na użyty zestaw tekstur jest spójny graficznie. Dziedziczenie zrealizowane zgodnie z wymaganiami, brakuje natomiast wykorzystania polimorfii i alokacji pamięci.  Plik kropka .exe nie działa poprawnie (aplikacja nie wyrzuca błędu ale zamyka się zaraz po uruchomieniu). Ilość przygotowanej rozgrywki jest stosunkowo niewielka ale wykonana bardzo solidnie. Pewnym mankamentem jest również bardzo krótki plik readme

Proponuję ocenę projektu na 82,5%
